
//Product
export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

// Change theme 
export const CHANGE_THEME_COLOR = 'CHANGE_THEME_COLOR';
export const CHANGE_THEME_FONT_FAMILY = 'CHANGE_THEME_FONT_FAMILY';
export const CHANGE_THEME_FONT_SIZE = 'CHANGE_THEME_FONT_SIZE';

// List News 
export const GET_LIST_NEWS_REQUEST = 'GET_LIST_NEWS_REQUEST';
export const GET_LIST_NEWS_SUCCESS = 'GET_LIST_NEWS_SUCCESS';
export const GET_LIST_NEWS_FAILURE = 'GET_LIST_NEWS_FAILURE';

export const GET_MORE_LIST_NEWS_REQUEST = 'GET_MORE_LIST_NEWS_REQUEST';
export const GET_MORE_LIST_NEWS_SUCCESS = 'GET_MORE_LIST_NEWS_SUCCESS';
export const GET_MORE_LIST_NEWS_FAILURE = 'GET_MORE_LIST_NEWS_FAILURE';

export const GET_CATS_LIST_NEWS_REQUEST = 'GET_CATS_LIST_NEWS_REQUEST';
export const GET_CATS_LIST_NEWS_SUCCESS = 'GET_CATS_LIST_NEWS_SUCCESS';
export const GET_CATS_LIST_NEWS_FAILURE = 'GET_CATS_LIST_NEWS_FAILURE';
export const GET_MORE_CATS_LIST_NEWS_REQUEST = 'GET_MORE_CATS_LIST_NEWS_REQUEST';
export const GET_MORE_CATS_LIST_NEWS_SUCCESS = 'GET_MORE_CATS_LIST_NEWS_SUCCESS';
export const GET_MORE_CATS_LIST_NEWS_FAILURE = 'GET_MORE_CATS_LIST_NEWS_FAILURE';

// List Tab Bar 
export const GET_LIST_TAB_REQUEST = 'GET_LIST_TAB_REQUEST';
export const GET_LIST_TAB_SUCCESS = 'GET_LIST_TAB_SUCCESS';
export const GET_LIST_TAB_FAILURE = 'GET_LIST_TAB_FAILURE';

// SEARCH
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

// GET DETAIL NEWS
export const GET_DETAIL_NEWS_REQUEST = 'GET_DETAIL_NEWS_REQUEST';
export const GET_DETAIL_NEWS_SUCCESS = 'GET_DETAIL_NEWS_SUCCESS';
export const GET_DETAIL_NEWS_FAILURE = 'GET_DETAIL_NEWS_FAILURE';

// Data Tick
export const ADD_DATA_TICK = 'ADD_DATA_TICK';
export const REMOVE_DATA_TICK = 'REMOVE_DATA_TICK';

// Auto play video
export const AUTO_PLAY_VIDEO = 'AUTO_PLAY_VIDEO'

// GET DETAIL NEWS
export const GET_BANNER_REQUEST = 'GET_BANNER_REQUEST';
export const GET_BANNER_SUCCESS = 'GET_BANNER_SUCCESS';
export const GET_BANNER_FAILURE = 'GET_BANNER_FAILURE';